---
name: Deploy GO function
run-name: Deploy GO function. ${{ github.event.inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: string
        default: "dev"


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "APP_NAME=${{ github.event.inputs.app-name }}" # >> $GITHUB_ENV
          echo "APP_TYPE=${{ github.event.inputs.app-type }}" # >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" # >> $GITHUB_ENV
          echo "DEPLOY_LOGIN=${{ secrets.DEPLOY_LOGIN }}" # >> $GITHUB_ENV
          echo "DEPLOY_TOKEN=${{ secrets.DEPLOY_TOKEN }}" # >> $GITHUB_ENV
